# -*- coding: utf-8 -*-
"""
Demo of Improved RAG: Re-ranking, HyDE, Fusion Retrieval.

This script demonstrates all three techniques.
"""

import os
import sys

# Force UTF-8
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

import logging

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(message)s')
logger = logging.getLogger(__name__)

# Load .env
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


def demo_reranking():
    """Demo of Re-ranking."""
    print("\n" + "="*60)
    print("1. RE-RANKING")
    print("="*60)
    print("""
Sense: After initial search, documents are re-ordered
by real relevance using LLM analysis.

Example:
  Query: "How to create RAG system?"
  
  Before Re-ranking (vector search):
    1. Introduction to ML (score: 0.85)
    2. What is RAG (score: 0.80)  <- Most useful!
    3. Python for beginners (score: 0.75)
  
  After Re-ranking (LLM evaluation):
    1. What is RAG (score: 9.5)   <- Now first!
    2. Introduction to ML (score: 4.2)
    3. Python for beginners (score: 2.1)
""")

    from src.reranker import Reranker, Document
    
    # Example usage
    docs = [
        Document(
            id='1',
            text='RAG (Retrieval-Augmented Generation) is a method that combines information retrieval with text generation.',
            metadata={'source': 'doc1.pdf'},
            original_score=0.9
        ),
        Document(
            id='2',
            text='To cook borscht you need: beets, cabbage, potatoes, meat, onion, carrot. Cook for 2 hours.',
            metadata={'source': 'recept.pdf'},
            original_score=0.85
        ),
        Document(
            id='3',
            text='RAG systems use vector databases to store document embeddings and perform semantic search.',
            metadata={'source': 'doc2.pdf'},
            original_score=0.8
        ),
    ]
    
    reranker = Reranker(top_k=3)
    query = "What is RAG and how does it work?"
    ranked = reranker.rank(query, docs)
    
    print("Result:")
    for r in ranked:
        print(f"  {r.rank}. [score: {r.relevance_score:.1f}] {r.text[:50]}...")


def demo_hyde():
    """Demo of HyDE."""
    print("\n" + "="*60)
    print("2. HyDE (Hypothetical Document Embeddings)")
    print("="*60)
    print("""
Sense: LLM generates an "ideal answer" to the query,
then searches for documents similar to this answer.

Example:
  Query: "How to backup a database?"
  
  Hypothetical answer (generated by LLM):
    "To create a database backup you need:
     1. Use pg_dump command for PostgreSQL
     2. For MySQL - mysqldump
     3. Create dump of all tables
     4. Compress with gzip
     5. Save to safe location..."
  
  Search is performed on this answer, not the short query!

Why it works:
  - Query: 5-10 words
  - Hypothetical answer: 100-200 words
  - More intersection points for semantic search
  - LLM "knows" which documents are relevant
""")


def demo_fusion():
    """Demo of Fusion Retrieval."""
    print("\n" + "="*60)
    print("3. FUSION RETRIEVAL")
    print("="*60)
    print("""
Sense: Combine different search methods for better results.

Methods:
  1. Vector Search - semantic similarity
  2. Keyword Search (BM25) - exact word match
  3. LLM Search - logical inference

Fusion algorithms:
  
  RRF (Reciprocal Rank Fusion):
    score = weight / (k + rank)
    - Independent of absolute scores
    - Works well with different search types
  
  Score-based:
    score = w1*vector + w2*keyword + w3*llm
    - Takes into account weights of each method
    - Flexible configuration

Example:
  Query: "neural network training"
  
  Vector:  [doc1: 0.9, doc2: 0.7, doc3: 0.5]
  Keyword: [doc2: 1.0, doc4: 0.8, doc1: 0.3]
  LLM:     [doc1: 0.9, doc3: 0.6, doc2: 0.5]
  
  After Fusion:
  1. doc1 (strong in all sources)
  2. doc2 (strong in vector and keyword)
  3. doc3 (strong in vector)
""")


def demo_improved_rag():
    """Demo of full Improved RAG."""
    print("\n" + "="*60)
    print("4. IMPROVED RAG (Full pipeline)")
    print("="*60)
    print("""
Improved RAG combines all techniques:

  1. Candidate search (Vector / HyDE / Fusion)
  2. Re-ranking via LLM
  3. Answer generation

Usage:
  from src.improved_rag import improved_rag_query
  
  result = improved_rag_query(
      query="How does RAG work?",
      index_path="output/vector_db/index.faiss",
      dataset_path="output/vector_db/dataset.json",
      use_reranking=True,
      use_hyde=False,
      use_fusion=False,
      verbose=True
  )
  
  print(result['answer'])
  print(result['sources'])
  print(result['metadata'])
""")


def demo_comparison():
    """Comparison of methods."""
    print("\n" + "="*60)
    print("5. COMPARISON OF METHODS")
    print("="*60)
    print("""
| Method      | What it improves | When to use                    |
|-------------|------------------|--------------------------------|
| Re-ranking  | Precision        | Few results, accuracy matters  |
| HyDE        | Recall           | Complex queries, few matches   |
| Fusion      | Balance          | Want to use everything         |

Effectiveness (approximate):
  - Re-ranking: +15-30% precision
  - HyDE: +10-20% recall  
  - Fusion: +20-40% combined

Cost (API calls):
  - Re-ranking: 1 LLM call per document
  - HyDE: 1 LLM call for generation + search
  - Fusion: up to 3x requests (each method)
""")


def main():
    """Run all demos."""
    print("""
============================================================
   DEMONSTRATION OF IMPROVED RAG
   Re-ranking + HyDE + Fusion Retrieval
============================================================
    """)
    
    demo_reranking()
    demo_hyde()
    demo_fusion()
    demo_improved_rag()
    demo_comparison()
    
    print("\n" + "="*60)
    print("To test with real database use:")
    print("  from src.improved_rag import improved_rag_query")
    print("="*60)


if __name__ == "__main__":
    main()
